input_dir: resumes
output_dir: json_output
ground_truth_path: resumes/ground_truth.json
print_each_resume: true
exts: [".pdf", ".docx"]

llm:
  api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # GROQ-API key
  endpoint: "https://api.groq.com/openai/v1/chat/completions"
  model: "llama-3.1-8b-instant"
  # model: ["gemma2-9b-it"]
  temperature: 0.0
  timeout_s: 30
  max_retries: 2
  min_call_interval_s: 62.0   # e.g., 62 for strict rate limits
  prompt_mode: "few"         # or "single"
  max_chars: 4000
  max_tokens: 256
